const express=require('express')
const router=express.Router()
const router_handler=require('../router_handler/user')
const petMessage=require('../router_handler/pet')
const device=require('../router_handler/device')
const  yanzheng=require('../auth')
// router.post('/login',router_handler.login)
router.post('/regUser',router_handler.regUser)
// router.get('/booksSearch',router_handler.booksSearch)
// router.get('/userSearch',router_handler.userSearch)
router.post('/userSearch',router_handler.userSearch)
router.post('/api/chat',router_handler.ai);
router.put('/forGetPwd',router_handler.forGectPwd)
router.post('/addPet',petMessage.addPet)
router.get('/findPet',petMessage.findPet)
router.put('/changeAccount',router_handler.ChangeAccount)
router.put('/ChangeUserName',router_handler.ChangeUserName)
router.put('/ChangePetMessage',petMessage.ChangePetMessage)
router.get('/FindPetHealthMessage',petMessage.FindPetHealthMessage)
router.post('/UpdateHealthMessage',petMessage.UpdateHealthMessage)
router.delete('/deletePet',petMessage.DeletePet)
router.post('/AddDevice',device.AddDevice)
router.get('/device_status',device.device_status)
module.exports=router
